spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartsearch
    username: smartsearch
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          timezone: UTC
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false   
  flyway:
    enabled: true  
    baseline-on-migrate: true
    baseline-version: 1
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.milvus.autoconfigure.MilvusVectorStoreAutoConfiguration
      - io.milvus.spring.autoconfigure.MilvusAutoConfiguration	
  ai:
   openai:
     api-key: ${OPENAI_API_KEY}
     chat:
       options:
         model: gpt-4.1-mini
     embedding:
        options:
          model: text-embedding-3-small
smartsearch:
  embedding:
    dims: 1536
  kafka:
    ingest-topic: smartsearch.ingest.v1
    
     

  
server:
  address: 0.0.0.0
